import {
  SiPhp,
  SiJavascript,
  SiTypescript,
  SiC,
  SiCplusplus,
  SiMysql,
  SiPostgresql,
  SiMongodb,
  SiMongoose,
  SiRedis,
  SiPrisma,
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiBootstrap,
  SiFramer,
  SiGreensock,
  SiRedux,
  SiFigma,
  SiNodedotjs,
  SiExpress,
  SiLaravel,
  SiGraphql,
  SiJsonwebtokens,
  SiGit,
  SiGithubactions,
  SiDocker,
  SiNginx,
  SiVercel,
  SiRailway,
  SiPm2,
  SiJest,
  SiPostman,
  SiInsomnia, 
} from "react-icons/si";

export const SKILL_DATA = [
  {
    category: "Languages",
    items: [
      { name: "PHP", icon: SiPhp },
      { name: "JavaScript", icon: SiJavascript },
      { name: "TypeScript", icon: SiTypescript },
      { name: "C", icon: SiC },
      { name: "C++", icon: SiCplusplus },
      { name: "SQL", icon: SiMysql },
    ],
  },
  {
    category: "Frontend",
    items: [
      { name: "React", icon: SiReact },
      { name: "Next.js", icon: SiNextdotjs },
      { name: "Tailwind CSS", icon: SiTailwindcss },
      { name: "Bootstrap", icon: SiBootstrap },
      { name: "Framer Motion", icon: SiFramer },
      { name: "GSAP", icon: SiGreensock },
      { name: "Redux Toolkit", icon: SiRedux },
      { name: "Figma (UI/UX)", icon: SiFigma },
    ],
  },
  {
    category: "Backend",
    items: [
      { name: "Node.js", icon: SiNodedotjs },
      { name: "Express.js", icon: SiExpress },
      { name: "Laravel", icon: SiLaravel },
      { name: "REST API", icon: SiJsonwebtokens },
      { name: "GraphQL", icon: SiGraphql },
      { name: "JWT", icon: SiJsonwebtokens },
    ],
  },
  {
    category: "Database",
    items: [
      { name: "MongoDB", icon: SiMongodb },
      { name: "Mongoose", icon: SiMongoose },
      { name: "PostgreSQL", icon: SiPostgresql },
      { name: "MySQL", icon: SiMysql },
      { name: "Prisma ORM", icon: SiPrisma },
      { name: "Redis", icon: SiRedis },
    ],
  },
  {
    category: "DevOps",
    items: [
      { name: "Git", icon: SiGit },
      { name: "GitHub Actions", icon: SiGithubactions },
      { name: "Docker", icon: SiDocker },
      { name: "CI/CD", icon: SiGithubactions },
      { name: "Nginx", icon: SiNginx },
      { name: "Vercel", icon: SiVercel },
      { name: "Railway", icon: SiRailway },
      { name: "PM2", icon: SiPm2 },
    ],
  },
  {
    category: "Testing",
    items: [
      { name: "Jest", icon: SiJest },
      { name: "Postman", icon: SiPostman },
      { name: "Insomnia", icon: SiInsomnia },
    ],
  },
];
